@DaffaCatering.API_HostAddress = http://localhost:5247

### GET by ID
GET {{DaffaCatering.API_HostAddress}}/api/HeaderBahanBaku/BB0000016

### UPDATE
PUT {{DaffaCatering.API_HostAddress}}/api/HeaderBahanBaku/BB0000016
Content-Type: application/json

{
  "idBahanBaku": "BB0000016",
  "namaBahanBaku": "Test Bahan Baku Updated",
  "jenis": true,
  "status": false
}

### DELETE
DELETE {{DaffaCatering.API_HostAddress}}/api/HeaderBahanBaku/BB0000016